package main

func main() {
	// VarFunc()
	// TestAdd()
	// TestFunc()
	// TestStruct()
	// TestMethod()
	// TestMethod2()
	// TestMethod3()
	// TestInterface()
	// TestInterface2()
	// TestInterface3()
	// TestSlice()
	// TestString()
	// TestStruct1()
	// TestStruct2()
	// TestException()
	// TestException1()
	// TestException2()
	// testGoroutine()
	// testChannel()
	// testChannel2()
	// testChannel3()
	// testChannel4()
	// testChannel5()
	testChannel6()
}
